### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by ricardokleinklein** [ricardokleinklein/deepMultiSpeech#1]
## FUNDAMENTAL
- [x] Repair data: download clean, full dataset and merge data already available.
It's been observed that there are barely any sentence common to all the speakers, contrary to what the [website for noisy-VCTK corpus](https://datashare.is.ed.ac.uk/handle/10283/2791) says. Therefore, for parallel VC it is important to have all the data. Otherwise the number of samples available will be ridiculous.
- [x] Make Noisy-VCTK automatic pipeline for downloading data.
- [x] New metadata processing - following original tree structure.

### Input data:
- [x] SE training on 4 target speakers
- [x] SE test on 2 test speakers
- [x] VC training on 2? source speakers and same 4 target speakers
- [x] VC test on 2 test speakers and same 4 target speakers
- [x] VC as parallel-VC (same utterance source-target)
- [x] DTW between source Mel and target Mel
- [ ] TTS training on same 4 target speakers
- [ ] TTS test on 2 test speakers
- [x] User-defined number of source speakers in VC
- [x] User-defined number of target speakers in SE/VC

### Architecture:
- [x] SE modality
- [x] VC modality
- [ ] TTS modality
- [x] Body with several projection layers
- [x] Include non-linearities Body
- [ ] Change dimensionality at different layers - Change of concept

### Training:
- [ ] Split training of modalities - rest of model (speedup?)
- [x] Train jointly
- [ ] Extract feature maps obtained after modality nets
- [ ] Extract feature maps obtained after body

### Eval:
- [ ] Run SNR on SE results
